import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { loadDataLists } from '../../services/loadPages';
import { loadPageDetails } from '../../services/loadPageDetails';
import Link from 'next/link';
import Markdown from 'markdown-to-jsx';

function Page({ content }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Contentful Exercise Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.pageContainer}>
                <h1>{content.header}</h1>
                <div className={styles.backLink}>
                    <Link href={'/'}>
                        <a>Back to lists of pages</a>
                    </Link>
                </div>

                <div>
                    <Markdown>{content.content}</Markdown>
                </div>
                <footer id="footer">{content.footer}</footer>
            </div>
        </div>
    );
}

export async function getStaticPaths() {
    const data = await loadDataLists();

    return {
        paths: data,
        fallback: false
    };
}

export async function getStaticProps(context) {
    const { id } = context.params;
    const data = await loadPageDetails(id);

    const { header, content, footer } = data;

    return {
        props: {
            content: {
                id: id,
                header: header,
                content: content,
                footer: footer
            }
        }
    };
}

export default Page;
